const movieseventsdata=[
    {
      id: 1,
      title: "Lucky Baskar",
      type: "Movie",
      language: "Tamil",
      price: 150,
      category: "Action",
      imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCAyMyBOb3Y%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00412217-vucklcsaep-portrait.jpg",
    },
    {
      id: 2,
      title: "GOAT",
      type: "Movie",
      language: "Hindi",
      price: 200,
      category: "Drama",
      imageUrl: "https://example.com/movie2.jpg",
    },
    {
      id: 3,
      title: "International Clown Festival",
      type: "Event",
      language: "English",
      price: 500,
      category: "Comedy",
      imageUrl: "https://example.com/event1.jpg",
    },
    {
      id: 4,
      title: "Pushpa 2",
      type: "Movie",
      language: "Telugu",
      price: 180,
      category: "Action",
      imageUrl: "https://example.com/movie3.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
    {
      id: 5,
      title: "Classical Music Night",
      type: "Event",
      language: "Hindi",
      price: 300,
      category: "Music",
      imageUrl: "https://example.com/event2.jpg",
    },
  ];

  export default movieseventsdata;